# Generated by Django 2.0.6 on 2018-08-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(choices=[('python', 'python'), ('oracle', 'oracle'), ('linux', 'linux')], default='python', max_length=100),
        ),
    ]
